---
title: "Spaco_vignette"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GitHub Documents

This is an R Markdown format used for publishing markdown documents to GitHub. When you click the **Knit** button all R code chunks are run and a markdown file (.md) suitable for publishing to GitHub is generated.

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
#load liver data
devtools::load_all("~/SPACO")
data_dir="~/Liver_Organoid_project/scRNA_spatial_tissue/VX03_A006200136/cellranger/141895/outs"
slice = "~/Liver_Organoid_project/scRNA_spatial_tissue/VX03_A006200136/cellranger/141895/outs/spatial"
filename ="filtered_feature_bc_matrix.h5"
spatial_file = "tissue_positions_list.csv"
```

```{r}
SpaCoObject <- read_10x_for_spaco(data_dir = data_dir,slice = slice,filename =filename,variable_features_n = 3000,
                                  spatial_file = spatial_file, vars_to_regress = c("^mt-","^Hbb-"))
```

```{r include=FALSE}
SpaCoObject <- RunSCA(SpaCoObject, PC_criterion = "percent",
                      PC_value = .9, orthogonalResult = FALSE, compute_nSpacs = TRUE,
                      compute_projections = TRUE, nSim = 1000, nSpacQuantile = 0.05)

```

```{r}
data <- Load10X_Spatial(data.dir = data_dir, slice = slice, filename = filename, assay = "RNA", filter.matrix = TRUE)
data <- PercentageFeatureSet(data, pattern = "^mt-",col.name = "percent.mt" )
data <- PercentageFeatureSet(data, pattern = "^Hbb-",col.name = "percent.hb" )

data <- SCTransform(data, assay = "RNA", variable.features.n = 3000, vars.to.regress = c("percent.mt","percent.hb"))

data <- SPACO::subset_non_neighbour_cells(SpaCoObject,data)

data <- SPACO::spacs_to_seurat(SpaCoObject,data)
```

```{r}
SpaCoObject@nSpacs
DE_genes<- PValWrapperFunction_object(SpaCoObject, nSim = 1e3,nSpacs = 3)
DE_genes
```

```{r include=FALSE}
cc <- SpatialFeaturePlot(data,features = c("Spac_1","Spac_2","Spac_3","Spac_4"),combine = T)
data_2 <- RunPCA(data)
dd <- SpatialFeaturePlot(data_2,features = c("PC_1","PC_2","PC_3","PC_4"),combine = T)

data <- RunUMAP(data,reduction = "spaco",dims = 1:5,n.neighbors = 45)
data_2 <- RunUMAP(data_2,reduction = "pca",dims = 1:30)

nn <- FeaturePlot(data,features="Cyp2e1",cols=c("grey","blue1","darkred"),reduction = "spaco")
mm <- FeaturePlot(data_2,features="Cyp2e1",cols=c("grey","blue1","darkred"),reduction = "pca")

jj <- FeaturePlot(data,features="Cyp2e1",cols=c("grey","blue1","darkred"),reduction = "umap")
kk <- FeaturePlot(data_2,features="Cyp2e1",cols=c("grey","blue1","darkred"),reduction = "umap")

data <- FindNeighbors(data,reduction = "spaco" , dims = 1:5)
data_2 <- FindNeighbors(data_2,reduction = "pca" , dims = 1:30)

data <- FindClusters(data,resolution = 0.24)
data_2 <- FindClusters(data_2)

aa <- DimPlot(data,group.by="seurat_clusters")+ggtitle("SpaCo")
bb <- DimPlot(data_2,group.by="seurat_clusters")+ggtitle("Pca")
a <- DimPlot(data,reduction = "spaco")+ggtitle("SpaCo")
b <- DimPlot(data_2,reduction = "pca")+ggtitle("Pca")

rr <- SpatialDimPlot(data)+ggtitle("SpaCo")
qq <- SpatialDimPlot(data_2)+ggtitle("Pca")


```

```{r}
patchwork::wrap_plots(a,b,nn,mm,jj,kk,aa,bb,ncol=2)
a+b
nn+mm
jj+kk
aa+bb
```

